/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.ContinueWithRecoveryUi
import sh.ory.kratos.models.ContinueWithRecoveryUiFlow
import sh.ory.kratos.models.ContinueWithRedirectBrowserTo
import sh.ory.kratos.models.ContinueWithSetOrySessionToken
import sh.ory.kratos.models.ContinueWithSettingsUi
import sh.ory.kratos.models.ContinueWithVerificationUi

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("action")
sealed interface ContinueWith {

    @Serializable
    enum class Action(val value: kotlin.String) {
        @SerialName(value = "redirect_browser_to") REDIRECT_BROWSER_TO("redirect_browser_to"),
        @SerialName(value = "set_ory_session_token") SET_ORY_SESSION_TOKEN("set_ory_session_token"),
        @SerialName(value = "show_recovery_ui") SHOW_RECOVERY_UI("show_recovery_ui"),
        @SerialName(value = "show_settings_ui") SHOW_SETTINGS_UI("show_settings_ui"),
        @SerialName(value = "show_verification_ui") SHOW_VERIFICATION_UI("show_verification_ui");
    }

}