/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * It can either be `email` or `phone`
 *
 * Values: EMAIL,PHONE
 */
@Serializable
enum class CourierMessageType(val value: kotlin.String) {

    @SerialName(value = "email")
    EMAIL("email"),

    @SerialName(value = "phone")
    PHONE("phone");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CourierMessageType) "$data" else null

        /**
         * Returns a valid [CourierMessageType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CourierMessageType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

