/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Deleted Session Count
 *
 * @param count The number of sessions that were revoked.
 */
@Serializable

data class DeleteMySessionsCount (

    /* The number of sessions that were revoked. */
    @SerialName(value = "count")
    val count: kotlin.Long? = null

) {


}

