/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.GenericError

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Is sent when a flow is replaced by a different flow of the same class
 *
 * @param error 
 * @param useFlowId The flow ID that should be used for the new flow as it contains the correct messages.
 */
@Serializable

data class ErrorFlowReplaced (

    @SerialName(value = "error")
    val error: GenericError? = null,

    /* The flow ID that should be used for the new flow as it contains the correct messages. */
    @SerialName(value = "use_flow_id")
    val useFlowId: kotlin.String? = null

) {


}

