/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonObject

/**
 * 
 *
 * @param message Error message  The error's message.
 * @param code The status code
 * @param debug Debug information  This field is often not exposed to protect against leaking sensitive information.
 * @param details Further error details
 * @param id The error ID  Useful when trying to identify various errors in application logic.
 * @param reason A human-readable reason for the error
 * @param request The request ID  The request ID is often exposed internally in order to trace errors across service architectures. This is often a UUID.
 * @param status The status description
 */
@Serializable

data class GenericError (

    /* Error message  The error's message. */
    @SerialName(value = "message")
    val message: kotlin.String,

    /* The status code */
    @SerialName(value = "code")
    val code: kotlin.Long? = null,

    /* Debug information  This field is often not exposed to protect against leaking sensitive information. */
    @SerialName(value = "debug")
    val debug: kotlin.String? = null,

    /* Further error details */
    @Contextual @SerialName(value = "details")
    val details: JsonObject? = null,

    /* The error ID  Useful when trying to identify various errors in application logic. */
    @SerialName(value = "id")
    val id: kotlin.String? = null,

    /* A human-readable reason for the error */
    @SerialName(value = "reason")
    val reason: kotlin.String? = null,

    /* The request ID  The request ID is often exposed internally in order to trace errors across service architectures. This is often a UUID. */
    @SerialName(value = "request")
    val request: kotlin.String? = null,

    /* The status description */
    @SerialName(value = "status")
    val status: kotlin.String? = null

) {


}

