/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param initialAccessToken 
 * @param initialIdToken 
 * @param initialRefreshToken 
 * @param organization 
 * @param provider 
 * @param subject 
 */
@Serializable

data class IdentityCredentialsOidcProvider (

    @SerialName(value = "initial_access_token")
    val initialAccessToken: kotlin.String? = null,

    @SerialName(value = "initial_id_token")
    val initialIdToken: kotlin.String? = null,

    @SerialName(value = "initial_refresh_token")
    val initialRefreshToken: kotlin.String? = null,

    @SerialName(value = "organization")
    val organization: kotlin.String? = null,

    @SerialName(value = "provider")
    val provider: kotlin.String? = null,

    @SerialName(value = "subject")
    val subject: kotlin.String? = null

) {


}

