/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonObject

/**
 * An Identity JSON Schema Container
 *
 * @param id The ID of the Identity JSON Schema
 * @param schema The actual Identity JSON Schema
 */
@Serializable

data class IdentitySchemaContainer (

    /* The ID of the Identity JSON Schema */
    @SerialName(value = "id")
    val id: kotlin.String? = null,

    /* The actual Identity JSON Schema */
    @Contextual @SerialName(value = "schema")
    val schema: JsonObject? = null

) {


}

