/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param address The address for this code
 * @param channel 
 */
@Serializable

data class IdentityCredentialsCodeAddress (

    /* The address for this code */
    @SerialName(value = "address")
    val address: kotlin.String? = null,

    @SerialName(value = "channel")
    val channel: kotlin.String? = null

) {


}

