/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonObject

/**
 * Credentials represents a specific credential type
 *
 * @param config 
 * @param createdAt CreatedAt is a helper struct field for gobuffalo.pop.
 * @param identifiers Identifiers represents a list of unique identifiers this credential type matches.
 * @param type Type discriminates between different types of credentials. password CredentialsTypePassword oidc CredentialsTypeOIDC totp CredentialsTypeTOTP lookup_secret CredentialsTypeLookup webauthn CredentialsTypeWebAuthn code CredentialsTypeCodeAuth passkey CredentialsTypePasskey profile CredentialsTypeProfile link_recovery CredentialsTypeRecoveryLink  CredentialsTypeRecoveryLink is a special credential type linked to the link strategy (recovery flow).  It is not used within the credentials object itself. code_recovery CredentialsTypeRecoveryCode
 * @param updatedAt UpdatedAt is a helper struct field for gobuffalo.pop.
 * @param version Version refers to the version of the credential. Useful when changing the config schema.
 */
@Serializable

data class IdentityCredentials (

    @Contextual @SerialName(value = "config")
    val config: JsonObject? = null,

    /* CreatedAt is a helper struct field for gobuffalo.pop. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlinx.datetime.Instant? = null,

    /* Identifiers represents a list of unique identifiers this credential type matches. */
    @SerialName(value = "identifiers")
    val identifiers: kotlin.collections.List<kotlin.String>? = null,

    /* Type discriminates between different types of credentials. password CredentialsTypePassword oidc CredentialsTypeOIDC totp CredentialsTypeTOTP lookup_secret CredentialsTypeLookup webauthn CredentialsTypeWebAuthn code CredentialsTypeCodeAuth passkey CredentialsTypePasskey profile CredentialsTypeProfile link_recovery CredentialsTypeRecoveryLink  CredentialsTypeRecoveryLink is a special credential type linked to the link strategy (recovery flow).  It is not used within the credentials object itself. code_recovery CredentialsTypeRecoveryCode */
    @SerialName(value = "type")
    val type: IdentityCredentials.Type? = null,

    /* UpdatedAt is a helper struct field for gobuffalo.pop. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: kotlinx.datetime.Instant? = null,

    /* Version refers to the version of the credential. Useful when changing the config schema. */
    @SerialName(value = "version")
    val version: kotlin.Long? = null

) {

    /**
     * Type discriminates between different types of credentials. password CredentialsTypePassword oidc CredentialsTypeOIDC totp CredentialsTypeTOTP lookup_secret CredentialsTypeLookup webauthn CredentialsTypeWebAuthn code CredentialsTypeCodeAuth passkey CredentialsTypePasskey profile CredentialsTypeProfile link_recovery CredentialsTypeRecoveryLink  CredentialsTypeRecoveryLink is a special credential type linked to the link strategy (recovery flow).  It is not used within the credentials object itself. code_recovery CredentialsTypeRecoveryCode
     *
     * Values: PASSWORD,OIDC,TOTP,LOOKUP_SECRET,WEBAUTHN,CODE,PASSKEY,PROFILE,LINK_RECOVERY,CODE_RECOVERY
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "password") PASSWORD("password"),
        @SerialName(value = "oidc") OIDC("oidc"),
        @SerialName(value = "totp") TOTP("totp"),
        @SerialName(value = "lookup_secret") LOOKUP_SECRET("lookup_secret"),
        @SerialName(value = "webauthn") WEBAUTHN("webauthn"),
        @SerialName(value = "code") CODE("code"),
        @SerialName(value = "passkey") PASSKEY("passkey"),
        @SerialName(value = "profile") PROFILE("profile"),
        @SerialName(value = "link_recovery") LINK_RECOVERY("link_recovery"),
        @SerialName(value = "code_recovery") CODE_RECOVERY("code_recovery");
    }

}

