/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.IdentityWithCredentialsOidcConfigProvider
import sh.ory.kratos.models.IdentityWithCredentialsPasswordConfig

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param config 
 * @param providers A list of OpenID Connect Providers
 */
@Serializable

data class IdentityWithCredentialsOidcConfig (

    @SerialName(value = "config")
    val config: IdentityWithCredentialsPasswordConfig? = null,

    /* A list of OpenID Connect Providers */
    @SerialName(value = "providers")
    val providers: kotlin.collections.List<IdentityWithCredentialsOidcConfigProvider>? = null

) {


}

