/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.IdentityCredentialsCodeAddress

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * CredentialsCode represents a one time login/registration code
 *
 * @param addresses 
 */
@Serializable

data class IdentityCredentialsCode (

    @SerialName(value = "addresses")
    val addresses: kotlin.collections.List<IdentityCredentialsCodeAddress>? = null

) {


}

