/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.IdentityWithCredentialsOidcConfig

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Create Identity and Import Social Sign In Credentials
 *
 * @param config 
 */
@Serializable

data class IdentityWithCredentialsOidc (

    @SerialName(value = "config")
    val config: IdentityWithCredentialsOidcConfig? = null

) {


}

