/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonObject

/**
 * Response for a single identity patch
 *
 * @param action The action for this specific patch create ActionCreate  Create this identity. error ActionError  Error indicates that the patch failed.
 * @param error 
 * @param identity The identity ID payload of this patch
 * @param patchId The ID of this patch response, if an ID was specified in the patch.
 */
@Serializable

data class IdentityPatchResponse (

    /* The action for this specific patch create ActionCreate  Create this identity. error ActionError  Error indicates that the patch failed. */
    @SerialName(value = "action")
    val action: IdentityPatchResponse.Action? = null,

    @Contextual @SerialName(value = "error")
    val error: JsonObject? = null,

    /* The identity ID payload of this patch */
    @SerialName(value = "identity")
    val identity: kotlin.String? = null,

    /* The ID of this patch response, if an ID was specified in the patch. */
    @SerialName(value = "patch_id")
    val patchId: kotlin.String? = null

) {

    /**
     * The action for this specific patch create ActionCreate  Create this identity. error ActionError  Error indicates that the patch failed.
     *
     * Values: CREATE,ERROR
     */
    @Serializable
    enum class Action(val value: kotlin.String) {
        @SerialName(value = "create") CREATE("create"),
        @SerialName(value = "error") ERROR("error");
    }

}

