/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param errors Errors contains a list of errors that caused the not ready status.
 */
@Serializable

data class IsReady503Response (

    /* Errors contains a list of errors that caused the not ready status. */
    @SerialName(value = "errors")
    val errors: kotlin.collections.Map<kotlin.String, kotlin.String>

) {


}

