/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.CourierMessageStatus
import sh.ory.kratos.models.CourierMessageType
import sh.ory.kratos.models.MessageDispatch

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param body 
 * @param createdAt CreatedAt is a helper struct field for gobuffalo.pop.
 * @param id 
 * @param recipient 
 * @param sendCount 
 * @param status 
 * @param subject 
 * @param templateType  recovery_invalid TypeRecoveryInvalid recovery_valid TypeRecoveryValid recovery_code_invalid TypeRecoveryCodeInvalid recovery_code_valid TypeRecoveryCodeValid verification_invalid TypeVerificationInvalid verification_valid TypeVerificationValid verification_code_invalid TypeVerificationCodeInvalid verification_code_valid TypeVerificationCodeValid stub TypeTestStub login_code_valid TypeLoginCodeValid registration_code_valid TypeRegistrationCodeValid
 * @param type 
 * @param updatedAt UpdatedAt is a helper struct field for gobuffalo.pop.
 * @param channel 
 * @param dispatches Dispatches store information about the attempts of delivering a message May contain an error if any happened, or just the `success` state.
 */
@Serializable

data class Message (

    @SerialName(value = "body")
    val body: kotlin.String,

    /* CreatedAt is a helper struct field for gobuffalo.pop. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "recipient")
    val recipient: kotlin.String,

    @SerialName(value = "send_count")
    val sendCount: kotlin.Long,

    @Contextual @SerialName(value = "status")
    val status: CourierMessageStatus,

    @SerialName(value = "subject")
    val subject: kotlin.String,

    /*  recovery_invalid TypeRecoveryInvalid recovery_valid TypeRecoveryValid recovery_code_invalid TypeRecoveryCodeInvalid recovery_code_valid TypeRecoveryCodeValid verification_invalid TypeVerificationInvalid verification_valid TypeVerificationValid verification_code_invalid TypeVerificationCodeInvalid verification_code_valid TypeVerificationCodeValid stub TypeTestStub login_code_valid TypeLoginCodeValid registration_code_valid TypeRegistrationCodeValid */
    @SerialName(value = "template_type")
    val templateType: Message.TemplateType,

    @Contextual @SerialName(value = "type")
    val type: CourierMessageType,

    /* UpdatedAt is a helper struct field for gobuffalo.pop. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: kotlinx.datetime.Instant,

    @SerialName(value = "channel")
    val channel: kotlin.String? = null,

    /* Dispatches store information about the attempts of delivering a message May contain an error if any happened, or just the `success` state. */
    @SerialName(value = "dispatches")
    val dispatches: kotlin.collections.List<MessageDispatch>? = null

) {

    /**
     *  recovery_invalid TypeRecoveryInvalid recovery_valid TypeRecoveryValid recovery_code_invalid TypeRecoveryCodeInvalid recovery_code_valid TypeRecoveryCodeValid verification_invalid TypeVerificationInvalid verification_valid TypeVerificationValid verification_code_invalid TypeVerificationCodeInvalid verification_code_valid TypeVerificationCodeValid stub TypeTestStub login_code_valid TypeLoginCodeValid registration_code_valid TypeRegistrationCodeValid
     *
     * Values: RECOVERY_INVALID,RECOVERY_VALID,RECOVERY_CODE_INVALID,RECOVERY_CODE_VALID,VERIFICATION_INVALID,VERIFICATION_VALID,VERIFICATION_CODE_INVALID,VERIFICATION_CODE_VALID,STUB,LOGIN_CODE_VALID,REGISTRATION_CODE_VALID
     */
    @Serializable
    enum class TemplateType(val value: kotlin.String) {
        @SerialName(value = "recovery_invalid") RECOVERY_INVALID("recovery_invalid"),
        @SerialName(value = "recovery_valid") RECOVERY_VALID("recovery_valid"),
        @SerialName(value = "recovery_code_invalid") RECOVERY_CODE_INVALID("recovery_code_invalid"),
        @SerialName(value = "recovery_code_valid") RECOVERY_CODE_VALID("recovery_code_valid"),
        @SerialName(value = "verification_invalid") VERIFICATION_INVALID("verification_invalid"),
        @SerialName(value = "verification_valid") VERIFICATION_VALID("verification_valid"),
        @SerialName(value = "verification_code_invalid") VERIFICATION_CODE_INVALID("verification_code_invalid"),
        @SerialName(value = "verification_code_valid") VERIFICATION_CODE_VALID("verification_code_valid"),
        @SerialName(value = "stub") STUB("stub"),
        @SerialName(value = "login_code_valid") LOGIN_CODE_VALID("login_code_valid"),
        @SerialName(value = "registration_code_valid") REGISTRATION_CODE_VALID("registration_code_valid");
    }

}

