/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.GenericError

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param redirectBrowserTo Points to where to redirect the user to next.
 * @param error 
 */
@Serializable

data class NeedsPrivilegedSessionError (

    /* Points to where to redirect the user to next. */
    @SerialName(value = "redirect_browser_to")
    val redirectBrowserTo: kotlin.String,

    @SerialName(value = "error")
    val error: GenericError? = null

) {


}

