/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.IdentityPatch

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Patch Identities Body
 *
 * @param identities Identities holds the list of patches to apply  required
 */
@Serializable

data class PatchIdentitiesBody (

    /* Identities holds the list of patches to apply  required */
    @SerialName(value = "identities")
    val identities: kotlin.collections.List<IdentityPatch>? = null

) {


}

