/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Perform Native Logout Request Body
 *
 * @param sessionToken The Session Token  Invalidate this session token.
 */
@Serializable

data class PerformNativeLogoutBody (

    /* The Session Token  Invalidate this session token. */
    @SerialName(value = "session_token")
    val sessionToken: kotlin.String

) {


}

