/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Used when an administrator creates a recovery code for an identity.
 *
 * @param recoveryCode RecoveryCode is the code that can be used to recover the account
 * @param recoveryLink RecoveryLink with flow  This link opens the recovery UI with an empty `code` field.
 * @param expiresAt Expires At is the timestamp of when the recovery flow expires  The timestamp when the recovery code expires.
 */
@Serializable

data class RecoveryCodeForIdentity (

    /* RecoveryCode is the code that can be used to recover the account */
    @SerialName(value = "recovery_code")
    val recoveryCode: kotlin.String,

    /* RecoveryLink with flow  This link opens the recovery UI with an empty `code` field. */
    @SerialName(value = "recovery_link")
    val recoveryLink: kotlin.String,

    /* Expires At is the timestamp of when the recovery flow expires  The timestamp when the recovery code expires. */
    @Contextual @SerialName(value = "expires_at")
    val expiresAt: kotlinx.datetime.Instant? = null

) {


}

