/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Used when an administrator creates a recovery link for an identity.
 *
 * @param recoveryLink Recovery Link  This link can be used to recover the account.
 * @param expiresAt Recovery Link Expires At  The timestamp when the recovery link expires.
 */
@Serializable

data class RecoveryLinkForIdentity (

    /* Recovery Link  This link can be used to recover the account. */
    @SerialName(value = "recovery_link")
    val recoveryLink: kotlin.String,

    /* Recovery Link Expires At  The timestamp when the recovery link expires. */
    @Contextual @SerialName(value = "expires_at")
    val expiresAt: kotlinx.datetime.Instant? = null

) {


}

