/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.GenericError

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Is sent when a flow is expired
 *
 * @param error 
 * @param expiredAt When the flow has expired
 * @param since A Duration represents the elapsed time between two instants as an int64 nanosecond count. The representation limits the largest representable duration to approximately 290 years.
 * @param useFlowId The flow ID that should be used for the new flow as it contains the correct messages.
 */
@Serializable

data class SelfServiceFlowExpiredError (

    @SerialName(value = "error")
    val error: GenericError? = null,

    /* When the flow has expired */
    @Contextual @SerialName(value = "expired_at")
    val expiredAt: kotlinx.datetime.Instant? = null,

    /* A Duration represents the elapsed time between two instants as an int64 nanosecond count. The representation limits the largest representable duration to approximately 290 years. */
    @SerialName(value = "since")
    val since: kotlin.Long? = null,

    /* The flow ID that should be used for the new flow as it contains the correct messages. */
    @SerialName(value = "use_flow_id")
    val useFlowId: kotlin.String? = null

) {


}

