/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.UiNode
import sh.ory.kratos.models.UiText

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Container represents a HTML Form. The container can work with both HTTP Form and JSON requests
 *
 * @param action Action should be used as the form action URL `<form action=\"{{ .Action }}\" method=\"post\">`.
 * @param method Method is the form method (e.g. POST)
 * @param nodes 
 * @param messages 
 */
@Serializable

data class UiContainer (

    /* Action should be used as the form action URL `<form action=\"{{ .Action }}\" method=\"post\">`. */
    @SerialName(value = "action")
    val action: kotlin.String,

    /* Method is the form method (e.g. POST) */
    @SerialName(value = "method")
    val method: kotlin.String,

    @SerialName(value = "nodes")
    val nodes: kotlin.collections.List<UiNode>,

    @SerialName(value = "messages")
    val messages: kotlin.collections.List<UiText>? = null

) {


}

