/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.UiText

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param href The link's href (destination) URL.  format: uri
 * @param id A unique identifier
 * @param title
 */
@Serializable
@SerialName("a")
data class UiNodeAnchorAttributes (

    /* The link's href (destination) URL.  format: uri */
    @SerialName(value = "href")
    val href: kotlin.String,

    /* A unique identifier */
    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "title")
    val title: UiText

) : UiNodeAttributes

