/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.UiNodeAnchorAttributes
import sh.ory.kratos.models.UiNodeImageAttributes
import sh.ory.kratos.models.UiNodeInputAttributes
import sh.ory.kratos.models.UiNodeScriptAttributes
import sh.ory.kratos.models.UiNodeTextAttributes
import sh.ory.kratos.models.UiText

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("node_type")
sealed interface UiNodeAttributes