/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.UiNodeAttributes
import sh.ory.kratos.models.UiNodeMeta
import sh.ory.kratos.models.UiText

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Nodes are represented as HTML elements or their native UI equivalents. For example, a node can be an `<img>` tag, or an `<input element>` but also `some plain text`.
 *
 * @param attributes 
 * @param group Group specifies which group (e.g. password authenticator) this node belongs to. default DefaultGroup password PasswordGroup oidc OpenIDConnectGroup profile ProfileGroup link LinkGroup code CodeGroup totp TOTPGroup lookup_secret LookupGroup webauthn WebAuthnGroup passkey PasskeyGroup identifier_first IdentifierFirstGroup
 * @param messages 
 * @param meta 
 * @param type The node's type text Text input Input img Image a Anchor script Script
 */
@Serializable

data class UiNode (

    @SerialName(value = "attributes")
    val attributes: UiNodeAttributes,

    /* Group specifies which group (e.g. password authenticator) this node belongs to. default DefaultGroup password PasswordGroup oidc OpenIDConnectGroup profile ProfileGroup link LinkGroup code CodeGroup totp TOTPGroup lookup_secret LookupGroup webauthn WebAuthnGroup passkey PasskeyGroup identifier_first IdentifierFirstGroup */
    @SerialName(value = "group")
    val group: UiNode.Group,

    @SerialName(value = "messages")
    val messages: kotlin.collections.List<UiText>,

    @SerialName(value = "meta")
    val meta: UiNodeMeta,

    /* The node's type text Text input Input img Image a Anchor script Script */
    @SerialName(value = "type")
    val type: UiNode.Type

) {

    /**
     * Group specifies which group (e.g. password authenticator) this node belongs to. default DefaultGroup password PasswordGroup oidc OpenIDConnectGroup profile ProfileGroup link LinkGroup code CodeGroup totp TOTPGroup lookup_secret LookupGroup webauthn WebAuthnGroup passkey PasskeyGroup identifier_first IdentifierFirstGroup
     *
     * Values: DEFAULT,PASSWORD,OIDC,PROFILE,LINK,CODE,TOTP,LOOKUP_SECRET,WEBAUTHN,PASSKEY,IDENTIFIER_FIRST
     */
    @Serializable
    enum class Group(val value: kotlin.String) {
        @SerialName(value = "default") DEFAULT("default"),
        @SerialName(value = "password") PASSWORD("password"),
        @SerialName(value = "oidc") OIDC("oidc"),
        @SerialName(value = "profile") PROFILE("profile"),
        @SerialName(value = "link") LINK("link"),
        @SerialName(value = "code") CODE("code"),
        @SerialName(value = "totp") TOTP("totp"),
        @SerialName(value = "lookup_secret") LOOKUP_SECRET("lookup_secret"),
        @SerialName(value = "webauthn") WEBAUTHN("webauthn"),
        @SerialName(value = "passkey") PASSKEY("passkey"),
        @SerialName(value = "identifier_first") IDENTIFIER_FIRST("identifier_first");
    }
    /**
     * The node's type text Text input Input img Image a Anchor script Script
     *
     * Values: TEXT,INPUT,IMG,A,SCRIPT
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "text") TEXT("text"),
        @SerialName(value = "input") INPUT("input"),
        @SerialName(value = "img") IMG("img"),
        @SerialName(value = "a") A("a"),
        @SerialName(value = "script") SCRIPT("script");
    }

}

