/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.UiText

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonObject

/**
 * InputAttributes represents the attributes of an input node
 *
 * @param disabled Sets the input's disabled field to true or false.
 * @param name The input's element name.
 * @param type The input's element type. text InputAttributeTypeText password InputAttributeTypePassword number InputAttributeTypeNumber checkbox InputAttributeTypeCheckbox hidden InputAttributeTypeHidden email InputAttributeTypeEmail tel InputAttributeTypeTel submit InputAttributeTypeSubmit button InputAttributeTypeButton datetime-local InputAttributeTypeDateTimeLocal date InputAttributeTypeDate url InputAttributeTypeURI
 * @param autocomplete The autocomplete attribute for the input. email InputAttributeAutocompleteEmail tel InputAttributeAutocompleteTel url InputAttributeAutocompleteUrl current-password InputAttributeAutocompleteCurrentPassword new-password InputAttributeAutocompleteNewPassword one-time-code InputAttributeAutocompleteOneTimeCode
 * @param label 
 * @param maxlength MaxLength may contain the input's maximum length.
 * @param onclick OnClick may contain javascript which should be executed on click. This is primarily used for WebAuthn.  Deprecated: Using OnClick requires the use of eval() which is a security risk. Use OnClickTrigger instead.
 * @param onclickTrigger OnClickTrigger may contain a WebAuthn trigger which should be executed on click.  The trigger maps to a JavaScript function provided by Ory, which triggers actions such as PassKey registration or login. oryWebAuthnRegistration WebAuthnTriggersWebAuthnRegistration oryWebAuthnLogin WebAuthnTriggersWebAuthnLogin oryPasskeyLogin WebAuthnTriggersPasskeyLogin oryPasskeyLoginAutocompleteInit WebAuthnTriggersPasskeyLoginAutocompleteInit oryPasskeyRegistration WebAuthnTriggersPasskeyRegistration oryPasskeySettingsRegistration WebAuthnTriggersPasskeySettingsRegistration
 * @param onload OnLoad may contain javascript which should be executed on load. This is primarily used for WebAuthn.  Deprecated: Using OnLoad requires the use of eval() which is a security risk. Use OnLoadTrigger instead.
 * @param onloadTrigger OnLoadTrigger may contain a WebAuthn trigger which should be executed on load.  The trigger maps to a JavaScript function provided by Ory, which triggers actions such as PassKey registration or login. oryWebAuthnRegistration WebAuthnTriggersWebAuthnRegistration oryWebAuthnLogin WebAuthnTriggersWebAuthnLogin oryPasskeyLogin WebAuthnTriggersPasskeyLogin oryPasskeyLoginAutocompleteInit WebAuthnTriggersPasskeyLoginAutocompleteInit oryPasskeyRegistration WebAuthnTriggersPasskeyRegistration oryPasskeySettingsRegistration WebAuthnTriggersPasskeySettingsRegistration
 * @param pattern The input's pattern.
 * @param required Mark this input field as required.
 * @param `value` The input's value.
 */
@Serializable
@SerialName("input")
data class UiNodeInputAttributes (

    /* Sets the input's disabled field to true or false. */
    @SerialName(value = "disabled")
    val disabled: kotlin.Boolean,

    /* The input's element name. */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* The input's element type. text InputAttributeTypeText password InputAttributeTypePassword number InputAttributeTypeNumber checkbox InputAttributeTypeCheckbox hidden InputAttributeTypeHidden email InputAttributeTypeEmail tel InputAttributeTypeTel submit InputAttributeTypeSubmit button InputAttributeTypeButton datetime-local InputAttributeTypeDateTimeLocal date InputAttributeTypeDate url InputAttributeTypeURI */
    @SerialName(value = "type")
    val type: UiNodeInputAttributes.Type,

    /* The autocomplete attribute for the input. email InputAttributeAutocompleteEmail tel InputAttributeAutocompleteTel url InputAttributeAutocompleteUrl current-password InputAttributeAutocompleteCurrentPassword new-password InputAttributeAutocompleteNewPassword one-time-code InputAttributeAutocompleteOneTimeCode */
    @SerialName(value = "autocomplete")
    val autocomplete: UiNodeInputAttributes.Autocomplete? = null,

    @SerialName(value = "label")
    val label: UiText? = null,

    /* MaxLength may contain the input's maximum length. */
    @SerialName(value = "maxlength")
    val maxlength: kotlin.Long? = null,

    /* OnClick may contain javascript which should be executed on click. This is primarily used for WebAuthn.  Deprecated: Using OnClick requires the use of eval() which is a security risk. Use OnClickTrigger instead. */
    @SerialName(value = "onclick")
    val onclick: kotlin.String? = null,

    /* OnClickTrigger may contain a WebAuthn trigger which should be executed on click.  The trigger maps to a JavaScript function provided by Ory, which triggers actions such as PassKey registration or login. oryWebAuthnRegistration WebAuthnTriggersWebAuthnRegistration oryWebAuthnLogin WebAuthnTriggersWebAuthnLogin oryPasskeyLogin WebAuthnTriggersPasskeyLogin oryPasskeyLoginAutocompleteInit WebAuthnTriggersPasskeyLoginAutocompleteInit oryPasskeyRegistration WebAuthnTriggersPasskeyRegistration oryPasskeySettingsRegistration WebAuthnTriggersPasskeySettingsRegistration */
    @SerialName(value = "onclickTrigger")
    val onclickTrigger: UiNodeInputAttributes.OnclickTrigger? = null,

    /* OnLoad may contain javascript which should be executed on load. This is primarily used for WebAuthn.  Deprecated: Using OnLoad requires the use of eval() which is a security risk. Use OnLoadTrigger instead. */
    @SerialName(value = "onload")
    val onload: kotlin.String? = null,

    /* OnLoadTrigger may contain a WebAuthn trigger which should be executed on load.  The trigger maps to a JavaScript function provided by Ory, which triggers actions such as PassKey registration or login. oryWebAuthnRegistration WebAuthnTriggersWebAuthnRegistration oryWebAuthnLogin WebAuthnTriggersWebAuthnLogin oryPasskeyLogin WebAuthnTriggersPasskeyLogin oryPasskeyLoginAutocompleteInit WebAuthnTriggersPasskeyLoginAutocompleteInit oryPasskeyRegistration WebAuthnTriggersPasskeyRegistration oryPasskeySettingsRegistration WebAuthnTriggersPasskeySettingsRegistration */
    @SerialName(value = "onloadTrigger")
    val onloadTrigger: UiNodeInputAttributes.OnloadTrigger? = null,

    /* The input's pattern. */
    @SerialName(value = "pattern")
    val pattern: kotlin.String? = null,

    /* Mark this input field as required. */
    @SerialName(value = "required")
    val required: kotlin.Boolean? = null,

    /* The input's value. */
    @SerialName(value = "value")
    val `value`: String? = null

) : UiNodeAttributes {

    /**
     * The input's element type. text InputAttributeTypeText password InputAttributeTypePassword number InputAttributeTypeNumber checkbox InputAttributeTypeCheckbox hidden InputAttributeTypeHidden email InputAttributeTypeEmail tel InputAttributeTypeTel submit InputAttributeTypeSubmit button InputAttributeTypeButton datetime-local InputAttributeTypeDateTimeLocal date InputAttributeTypeDate url InputAttributeTypeURI
     *
     * Values: TEXT,PASSWORD,NUMBER,CHECKBOX,HIDDEN,EMAIL,TEL,SUBMIT,BUTTON,DATETIME_MINUS_LOCAL,DATE,URL
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "text") TEXT("text"),
        @SerialName(value = "password") PASSWORD("password"),
        @SerialName(value = "number") NUMBER("number"),
        @SerialName(value = "checkbox") CHECKBOX("checkbox"),
        @SerialName(value = "hidden") HIDDEN("hidden"),
        @SerialName(value = "email") EMAIL("email"),
        @SerialName(value = "tel") TEL("tel"),
        @SerialName(value = "submit") SUBMIT("submit"),
        @SerialName(value = "button") BUTTON("button"),
        @SerialName(value = "datetime-local") DATETIME_MINUS_LOCAL("datetime-local"),
        @SerialName(value = "date") DATE("date"),
        @SerialName(value = "url") URL("url");
    }
    /**
     * The autocomplete attribute for the input. email InputAttributeAutocompleteEmail tel InputAttributeAutocompleteTel url InputAttributeAutocompleteUrl current-password InputAttributeAutocompleteCurrentPassword new-password InputAttributeAutocompleteNewPassword one-time-code InputAttributeAutocompleteOneTimeCode
     *
     * Values: EMAIL,TEL,URL,CURRENT_MINUS_PASSWORD,NEW_MINUS_PASSWORD,ONE_MINUS_TIME_MINUS_CODE
     */
    @Serializable
    enum class Autocomplete(val value: kotlin.String) {
        @SerialName(value = "email") EMAIL("email"),
        @SerialName(value = "tel") TEL("tel"),
        @SerialName(value = "url") URL("url"),
        @SerialName(value = "current-password") CURRENT_MINUS_PASSWORD("current-password"),
        @SerialName(value = "new-password") NEW_MINUS_PASSWORD("new-password"),
        @SerialName(value = "one-time-code") ONE_MINUS_TIME_MINUS_CODE("one-time-code");
    }
    /**
     * OnClickTrigger may contain a WebAuthn trigger which should be executed on click.  The trigger maps to a JavaScript function provided by Ory, which triggers actions such as PassKey registration or login. oryWebAuthnRegistration WebAuthnTriggersWebAuthnRegistration oryWebAuthnLogin WebAuthnTriggersWebAuthnLogin oryPasskeyLogin WebAuthnTriggersPasskeyLogin oryPasskeyLoginAutocompleteInit WebAuthnTriggersPasskeyLoginAutocompleteInit oryPasskeyRegistration WebAuthnTriggersPasskeyRegistration oryPasskeySettingsRegistration WebAuthnTriggersPasskeySettingsRegistration
     *
     * Values: ORY_WEB_AUTHN_REGISTRATION,ORY_WEB_AUTHN_LOGIN,ORY_PASSKEY_LOGIN,ORY_PASSKEY_LOGIN_AUTOCOMPLETE_INIT,ORY_PASSKEY_REGISTRATION,ORY_PASSKEY_SETTINGS_REGISTRATION
     */
    @Serializable
    enum class OnclickTrigger(val value: kotlin.String) {
        @SerialName(value = "oryWebAuthnRegistration") ORY_WEB_AUTHN_REGISTRATION("oryWebAuthnRegistration"),
        @SerialName(value = "oryWebAuthnLogin") ORY_WEB_AUTHN_LOGIN("oryWebAuthnLogin"),
        @SerialName(value = "oryPasskeyLogin") ORY_PASSKEY_LOGIN("oryPasskeyLogin"),
        @SerialName(value = "oryPasskeyLoginAutocompleteInit") ORY_PASSKEY_LOGIN_AUTOCOMPLETE_INIT("oryPasskeyLoginAutocompleteInit"),
        @SerialName(value = "oryPasskeyRegistration") ORY_PASSKEY_REGISTRATION("oryPasskeyRegistration"),
        @SerialName(value = "oryPasskeySettingsRegistration") ORY_PASSKEY_SETTINGS_REGISTRATION("oryPasskeySettingsRegistration");
    }
    /**
     * OnLoadTrigger may contain a WebAuthn trigger which should be executed on load.  The trigger maps to a JavaScript function provided by Ory, which triggers actions such as PassKey registration or login. oryWebAuthnRegistration WebAuthnTriggersWebAuthnRegistration oryWebAuthnLogin WebAuthnTriggersWebAuthnLogin oryPasskeyLogin WebAuthnTriggersPasskeyLogin oryPasskeyLoginAutocompleteInit WebAuthnTriggersPasskeyLoginAutocompleteInit oryPasskeyRegistration WebAuthnTriggersPasskeyRegistration oryPasskeySettingsRegistration WebAuthnTriggersPasskeySettingsRegistration
     *
     * Values: ORY_WEB_AUTHN_REGISTRATION,ORY_WEB_AUTHN_LOGIN,ORY_PASSKEY_LOGIN,ORY_PASSKEY_LOGIN_AUTOCOMPLETE_INIT,ORY_PASSKEY_REGISTRATION,ORY_PASSKEY_SETTINGS_REGISTRATION
     */
    @Serializable
    enum class OnloadTrigger(val value: kotlin.String) {
        @SerialName(value = "oryWebAuthnRegistration") ORY_WEB_AUTHN_REGISTRATION("oryWebAuthnRegistration"),
        @SerialName(value = "oryWebAuthnLogin") ORY_WEB_AUTHN_LOGIN("oryWebAuthnLogin"),
        @SerialName(value = "oryPasskeyLogin") ORY_PASSKEY_LOGIN("oryPasskeyLogin"),
        @SerialName(value = "oryPasskeyLoginAutocompleteInit") ORY_PASSKEY_LOGIN_AUTOCOMPLETE_INIT("oryPasskeyLoginAutocompleteInit"),
        @SerialName(value = "oryPasskeyRegistration") ORY_PASSKEY_REGISTRATION("oryPasskeyRegistration"),
        @SerialName(value = "oryPasskeySettingsRegistration") ORY_PASSKEY_SETTINGS_REGISTRATION("oryPasskeySettingsRegistration");
    }

}

