/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param text The message text. Written in american english.
 * @param type The message type. info Info error Error success Success
 * @param context The message's context. Useful when customizing messages.
 */
@Serializable

data class UiText (

    @SerialName(value = "id")
    val id: kotlin.Long,

    /* The message text. Written in american english. */
    @SerialName(value = "text")
    val text: kotlin.String,

    /* The message type. info Info error Error success Success */
    @SerialName(value = "type")
    val type: UiText.Type,

    /* The message's context. Useful when customizing messages. */
    @Contextual @SerialName(value = "context")
    val context: String? = null

) {

    /**
     * The message type. info Info error Error success Success
     *
     * Values: INFO,ERROR,SUCCESS
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "info") INFO("info"),
        @SerialName(value = "error") ERROR("error"),
        @SerialName(value = "success") SUCCESS("success");
    }

}

