/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonObject

/**
 * Update Login flow using the code method
 *
 * @param csrfToken CSRFToken is the anti-CSRF token
 * @param address Address is the address to send the code to, in case that there are multiple addresses. This field is only used in two-factor flows and is ineffective for passwordless flows.
 * @param code Code is the 6 digits code sent to the user
 * @param identifier Identifier is the code identifier The identifier requires that the user has already completed the registration or settings with code flow.
 * @param resend Resend is set when the user wants to resend the code
 * @param transientPayload Transient data to pass along to any webhooks
 */
@Serializable
@SerialName("code")
data class UpdateLoginFlowWithCodeMethod (

    /* CSRFToken is the anti-CSRF token */
    @SerialName(value = "csrf_token")
    val csrfToken: kotlin.String,

    /* Address is the address to send the code to, in case that there are multiple addresses. This field is only used in two-factor flows and is ineffective for passwordless flows. */
    @SerialName(value = "address")
    val address: kotlin.String? = null,

    /* Code is the 6 digits code sent to the user */
    @SerialName(value = "code")
    val code: kotlin.String? = null,

    /* Identifier is the code identifier The identifier requires that the user has already completed the registration or settings with code flow. */
    @SerialName(value = "identifier")
    val identifier: kotlin.String? = null,

    /* Resend is set when the user wants to resend the code */
    @SerialName(value = "resend")
    val resend: kotlin.String? = null,

    /* Transient data to pass along to any webhooks */
    @Contextual @SerialName(value = "transient_payload")
    val transientPayload: JsonObject? = null

) : UpdateLoginFlowBody
