/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Update Settings Flow with Passkey Method
 *
 * @param csrfToken CSRFToken is the anti-CSRF token
 * @param passkeyRemove Remove a WebAuthn Security Key  This must contain the ID of the WebAuthN connection.
 * @param passkeySettingsRegister Register a WebAuthn Security Key  It is expected that the JSON returned by the WebAuthn registration process is included here.
 */
@Serializable
@SerialName("passkey")
data class UpdateSettingsFlowWithPasskeyMethod (

    /* CSRFToken is the anti-CSRF token */
    @SerialName(value = "csrf_token")
    val csrfToken: kotlin.String? = null,

    /* Remove a WebAuthn Security Key  This must contain the ID of the WebAuthN connection. */
    @SerialName(value = "passkey_remove")
    val passkeyRemove: kotlin.String? = null,

    /* Register a WebAuthn Security Key  It is expected that the JSON returned by the WebAuthn registration process is included here. */
    @SerialName(value = "passkey_settings_register")
    val passkeySettingsRegister: kotlin.String? = null

) : UpdateSettingsFlowBody