/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonObject

/**
 * Update Registration Flow with Code Method
 *
 * @param traits The identity's traits
 * @param code The OTP Code sent to the user
 * @param csrfToken The CSRF Token
 * @param resend Resend restarts the flow with a new code
 * @param transientPayload Transient data to pass along to any webhooks
 */
@Serializable
@SerialName("code")
data class UpdateRegistrationFlowWithCodeMethod (

    /* The identity's traits */
    @Contextual @SerialName(value = "traits")
    val traits: JsonObject,

    /* The OTP Code sent to the user */
    @SerialName(value = "code")
    val code: kotlin.String? = null,

    /* The CSRF Token */
    @SerialName(value = "csrf_token")
    val csrfToken: kotlin.String? = null,

    /* Resend restarts the flow with a new code */
    @SerialName(value = "resend")
    val resend: kotlin.String? = null,

    /* Transient data to pass along to any webhooks */
    @Contextual @SerialName(value = "transient_payload")
    val transientPayload: JsonObject? = null

) : UpdateRegistrationFlowBody
