/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.UpdateRegistrationFlowWithCodeMethod
import sh.ory.kratos.models.UpdateRegistrationFlowWithOidcMethod
import sh.ory.kratos.models.UpdateRegistrationFlowWithPasskeyMethod
import sh.ory.kratos.models.UpdateRegistrationFlowWithPasswordMethod
import sh.ory.kratos.models.UpdateRegistrationFlowWithProfileMethod
import sh.ory.kratos.models.UpdateRegistrationFlowWithWebAuthnMethod

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("method")
sealed interface UpdateRegistrationFlowBody
