/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.UpdateLoginFlowWithCodeMethod
import sh.ory.kratos.models.UpdateLoginFlowWithIdentifierFirstMethod
import sh.ory.kratos.models.UpdateLoginFlowWithLookupSecretMethod
import sh.ory.kratos.models.UpdateLoginFlowWithOidcMethod
import sh.ory.kratos.models.UpdateLoginFlowWithPasskeyMethod
import sh.ory.kratos.models.UpdateLoginFlowWithPasswordMethod
import sh.ory.kratos.models.UpdateLoginFlowWithTotpMethod
import sh.ory.kratos.models.UpdateLoginFlowWithWebAuthnMethod

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("method")
sealed interface UpdateLoginFlowBody
