/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonObject

/**
 * Update Settings Flow with Lookup Method
 *
 * @param csrfToken CSRFToken is the anti-CSRF token
 * @param lookupSecretConfirm If set to true will save the regenerated lookup secrets
 * @param lookupSecretDisable Disables this method if true.
 * @param lookupSecretRegenerate If set to true will regenerate the lookup secrets
 * @param lookupSecretReveal If set to true will reveal the lookup secrets
 * @param transientPayload Transient data to pass along to any webhooks
 */
@Serializable
@SerialName("lookup")
data class UpdateSettingsFlowWithLookupMethod (

    /* CSRFToken is the anti-CSRF token */
    @SerialName(value = "csrf_token")
    val csrfToken: kotlin.String? = null,

    /* If set to true will save the regenerated lookup secrets */
    @SerialName(value = "lookup_secret_confirm")
    val lookupSecretConfirm: kotlin.Boolean? = null,

    /* Disables this method if true. */
    @SerialName(value = "lookup_secret_disable")
    val lookupSecretDisable: kotlin.Boolean? = null,

    /* If set to true will regenerate the lookup secrets */
    @SerialName(value = "lookup_secret_regenerate")
    val lookupSecretRegenerate: kotlin.Boolean? = null,

    /* If set to true will reveal the lookup secrets */
    @SerialName(value = "lookup_secret_reveal")
    val lookupSecretReveal: kotlin.Boolean? = null,

    /* Transient data to pass along to any webhooks */
    @Contextual @SerialName(value = "transient_payload")
    val transientPayload: JsonObject? = null

) : UpdateSettingsFlowBody
