/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonObject

/**
 * Update Registration Flow with Passkey Method
 *
 * @param traits The identity's traits
 * @param csrfToken CSRFToken is the anti-CSRF token
 * @param passkeyRegister Register a WebAuthn Security Key  It is expected that the JSON returned by the WebAuthn registration process is included here.
 * @param transientPayload Transient data to pass along to any webhooks
 */
@Serializable
@SerialName("passkey")
data class UpdateRegistrationFlowWithPasskeyMethod (

    /* The identity's traits */
    @Contextual @SerialName(value = "traits")
    val traits: JsonObject,

    /* CSRFToken is the anti-CSRF token */
    @SerialName(value = "csrf_token")
    val csrfToken: kotlin.String? = null,

    /* Register a WebAuthn Security Key  It is expected that the JSON returned by the WebAuthn registration process is included here. */
    @SerialName(value = "passkey_register")
    val passkeyRegister: kotlin.String? = null,

    /* Transient data to pass along to any webhooks */
    @Contextual @SerialName(value = "transient_payload")
    val transientPayload: JsonObject? = null

) : UpdateRegistrationFlowBody
