/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonObject

/**
 * Update Login Flow with WebAuthn Method
 *
 * @param identifier Identifier is the email or username of the user trying to log in.
 * @param csrfToken Sending the anti-csrf token is only required for browser login flows.
 * @param transientPayload Transient data to pass along to any webhooks
 * @param webauthnLogin Login a WebAuthn Security Key  This must contain the ID of the WebAuthN connection.
 */
@Serializable
@SerialName("webauthn")
data class UpdateLoginFlowWithWebAuthnMethod (

    /* Identifier is the email or username of the user trying to log in. */
    @SerialName(value = "identifier")
    val identifier: kotlin.String,

    /* Sending the anti-csrf token is only required for browser login flows. */
    @SerialName(value = "csrf_token")
    val csrfToken: kotlin.String? = null,

    /* Transient data to pass along to any webhooks */
    @Contextual @SerialName(value = "transient_payload")
    val transientPayload: JsonObject? = null,

    /* Login a WebAuthn Security Key  This must contain the ID of the WebAuthN connection. */
    @SerialName(value = "webauthn_login")
    val webauthnLogin: kotlin.String? = null

) : UpdateLoginFlowBody
