/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonObject

/**
 * Update Registration Flow with Password Method
 *
 * @param password Password to sign the user up with
 * @param traits The identity's traits
 * @param csrfToken The CSRF Token
 * @param transientPayload Transient data to pass along to any webhooks
 */
@Serializable
@SerialName("password")
data class UpdateRegistrationFlowWithPasswordMethod(

    /* Password to sign the user up with */
    @SerialName(value = "password")
    val password: kotlin.String,

    /* The identity's traits */
    @Contextual @SerialName(value = "traits")
    val traits: JsonObject,

    /* The CSRF Token */
    @SerialName(value = "csrf_token")
    val csrfToken: kotlin.String? = null,

    /* Transient data to pass along to any webhooks */
    @Contextual @SerialName(value = "transient_payload")
    val transientPayload: JsonObject? = null

) : UpdateRegistrationFlowBody
