/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonObject

/**
 * Update Verification Flow with Link Method
 *
 * @param email Email to Verify  Needs to be set when initiating the flow. If the email is a registered verification email, a verification link will be sent. If the email is not known, a email with details on what happened will be sent instead.  format: email
 * @param csrfToken Sending the anti-csrf token is only required for browser login flows.
 * @param transientPayload Transient data to pass along to any webhooks
 */
@Serializable
@SerialName("link")
data class UpdateVerificationFlowWithLinkMethod (

    /* Email to Verify  Needs to be set when initiating the flow. If the email is a registered verification email, a verification link will be sent. If the email is not known, a email with details on what happened will be sent instead.  format: email */
    @SerialName(value = "email")
    val email: kotlin.String,

    /* Sending the anti-csrf token is only required for browser login flows. */
    @SerialName(value = "csrf_token")
    val csrfToken: kotlin.String? = null,

    /* Transient data to pass along to any webhooks */
    @Contextual @SerialName(value = "transient_payload")
    val transientPayload: JsonObject? = null

) : UpdateVerificationFlowBody
