/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import sh.ory.kratos.models.UpdateSettingsFlowWithLookupMethod
import sh.ory.kratos.models.UpdateSettingsFlowWithOidcMethod
import sh.ory.kratos.models.UpdateSettingsFlowWithPasskeyMethod
import sh.ory.kratos.models.UpdateSettingsFlowWithPasswordMethod
import sh.ory.kratos.models.UpdateSettingsFlowWithProfileMethod
import sh.ory.kratos.models.UpdateSettingsFlowWithTotpMethod
import sh.ory.kratos.models.UpdateSettingsFlowWithWebAuthnMethod

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("method")
sealed interface UpdateSettingsFlowBody

