/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonObject

/**
 * Update Settings Flow with TOTP Method
 *
 * @param csrfToken CSRFToken is the anti-CSRF token
 * @param totpCode ValidationTOTP must contain a valid TOTP based on the
 * @param totpUnlink UnlinkTOTP if true will remove the TOTP pairing, effectively removing the credential. This can be used to set up a new TOTP device.
 * @param transientPayload Transient data to pass along to any webhooks
 */
@Serializable
@SerialName("totp")
data class UpdateSettingsFlowWithTotpMethod (

    /* CSRFToken is the anti-CSRF token */
    @SerialName(value = "csrf_token")
    val csrfToken: kotlin.String? = null,

    /* ValidationTOTP must contain a valid TOTP based on the */
    @SerialName(value = "totp_code")
    val totpCode: kotlin.String? = null,

    /* UnlinkTOTP if true will remove the TOTP pairing, effectively removing the credential. This can be used to set up a new TOTP device. */
    @SerialName(value = "totp_unlink")
    val totpUnlink: kotlin.Boolean? = null,

    /* Transient data to pass along to any webhooks */
    @Contextual @SerialName(value = "transient_payload")
    val transientPayload: JsonObject? = null

) : UpdateSettingsFlowBody
