/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Update Login Flow with Passkey Method
 *
 * @param csrfToken Sending the anti-csrf token is only required for browser login flows.
 * @param passkeyLogin Login a WebAuthn Security Key  This must contain the ID of the WebAuthN connection.
 */
@Serializable
@SerialName("passkey")
data class UpdateLoginFlowWithPasskeyMethod (

    /* Sending the anti-csrf token is only required for browser login flows. */
    @SerialName(value = "csrf_token")
    val csrfToken: kotlin.String? = null,

    /* Login a WebAuthn Security Key  This must contain the ID of the WebAuthN connection. */
    @SerialName(value = "passkey_login")
    val passkeyLogin: kotlin.String? = null

) : UpdateLoginFlowBody