/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Update Login Flow with Lookup Secret Method
 *
 * @param lookupSecret The lookup secret.
 * @param csrfToken Sending the anti-csrf token is only required for browser login flows.
 */
@Serializable
@SerialName("lookup_secret")
data class UpdateLoginFlowWithLookupSecretMethod (

    /* The lookup secret. */
    @SerialName(value = "lookup_secret")
    val lookupSecret: kotlin.String,

    /* Sending the anti-csrf token is only required for browser login flows. */
    @SerialName(value = "csrf_token")
    val csrfToken: kotlin.String? = null

) : UpdateLoginFlowBody
