/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * VerifiableAddress is an identity's verifiable address
 *
 * @param status VerifiableAddressStatus must not exceed 16 characters as that is the limitation in the SQL Schema
 * @param `value` The address value  example foo@user.com
 * @param verified Indicates if the address has already been verified
 * @param via The delivery method
 * @param createdAt When this entry was created
 * @param id The ID
 * @param updatedAt When this entry was last updated
 * @param verifiedAt 
 */
@Serializable

data class VerifiableIdentityAddress (

    /* VerifiableAddressStatus must not exceed 16 characters as that is the limitation in the SQL Schema */
    @SerialName(value = "status")
    val status: kotlin.String,

    /* The address value  example foo@user.com */
    @SerialName(value = "value")
    val `value`: kotlin.String,

    /* Indicates if the address has already been verified */
    @SerialName(value = "verified")
    val verified: kotlin.Boolean,

    /* The delivery method */
    @SerialName(value = "via")
    val via: VerifiableIdentityAddress.Via,

    /* When this entry was created */
    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlinx.datetime.Instant? = null,

    /* The ID */
    @SerialName(value = "id")
    val id: kotlin.String? = null,

    /* When this entry was last updated */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: kotlinx.datetime.Instant? = null,

    @Contextual @SerialName(value = "verified_at")
    val verifiedAt: kotlinx.datetime.Instant? = null

) {

    /**
     * The delivery method
     *
     * Values: EMAIL,SMS
     */
    @Serializable
    enum class Via(val value: kotlin.String) {
        @SerialName(value = "email") EMAIL("email"),
        @SerialName(value = "sms") SMS("sms");
    }

}

