/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sh.ory.kratos.models.BatchPatchIdentitiesResponse
import sh.ory.kratos.models.IdentityPatchResponse

class BatchPatchIdentitiesResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BatchPatchIdentitiesResponse
        //val modelInstance = BatchPatchIdentitiesResponse()

        // to test the property `identities` - The patch responses for the individual identities.
        should("test identities") {
            // uncomment below to test the property
            //modelInstance.identities shouldBe ("TODO")
        }

    }
}
