/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sh.ory.kratos.models.ContinueWithRecoveryUi
import sh.ory.kratos.models.ContinueWithRecoveryUiFlow

class ContinueWithRecoveryUiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ContinueWithRecoveryUi
        //val modelInstance = ContinueWithRecoveryUi()

        // to test the property `action` - Action will always be `show_recovery_ui` show_recovery_ui ContinueWithActionShowRecoveryUIString
        should("test action") {
            // uncomment below to test the property
            //modelInstance.action shouldBe ("TODO")
        }

        // to test the property `flow`
        should("test flow") {
            // uncomment below to test the property
            //modelInstance.flow shouldBe ("TODO")
        }

    }
}
