/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sh.ory.kratos.models.IdentityWithCredentials
import sh.ory.kratos.models.IdentityWithCredentialsOidc
import sh.ory.kratos.models.IdentityWithCredentialsPassword

class IdentityWithCredentialsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IdentityWithCredentials
        //val modelInstance = IdentityWithCredentials()

        // to test the property `oidc`
        should("test oidc") {
            // uncomment below to test the property
            //modelInstance.oidc shouldBe ("TODO")
        }

        // to test the property `password`
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

    }
}
