/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sh.ory.kratos.models.IsReady503Response

class IsReady503ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IsReady503Response
        //val modelInstance = IsReady503Response()

        // to test the property `errors` - Errors contains a list of errors that caused the not ready status.
        should("test errors") {
            // uncomment below to test the property
            //modelInstance.errors shouldBe ("TODO")
        }

    }
}
