/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sh.ory.kratos.models.PerformNativeLogoutBody

class PerformNativeLogoutBodyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PerformNativeLogoutBody
        //val modelInstance = PerformNativeLogoutBody()

        // to test the property `sessionToken` - The Session Token  Invalidate this session token.
        should("test sessionToken") {
            // uncomment below to test the property
            //modelInstance.sessionToken shouldBe ("TODO")
        }

    }
}
