/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.kratos.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sh.ory.kratos.models.RegistrationFlowState

class RegistrationFlowStateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RegistrationFlowState
        //val modelInstance = RegistrationFlowState()

    }
}
